// Generated by jextract

package audio.fmod.panama;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct FMOD_DSP_STATE_DFT_FUNCTIONS {
 *     FMOD_DSP_DFT_FFTREAL_FUNC fftreal;
 *     FMOD_DSP_DFT_IFFTREAL_FUNC inversefftreal;
 * }
 * }
 */
public class FMOD_DSP_STATE_DFT_FUNCTIONS {

    FMOD_DSP_STATE_DFT_FUNCTIONS() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FmodCore.C_POINTER.withName("fftreal"),
        FmodCore.C_POINTER.withName("inversefftreal")
    ).withName("FMOD_DSP_STATE_DFT_FUNCTIONS");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final AddressLayout fftreal$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("fftreal"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * FMOD_DSP_DFT_FFTREAL_FUNC fftreal
     * }
     */
    public static final AddressLayout fftreal$layout() {
        return fftreal$LAYOUT;
    }

    private static final long fftreal$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * FMOD_DSP_DFT_FFTREAL_FUNC fftreal
     * }
     */
    public static final long fftreal$offset() {
        return fftreal$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * FMOD_DSP_DFT_FFTREAL_FUNC fftreal
     * }
     */
    public static MemorySegment fftreal(MemorySegment struct) {
        return struct.get(fftreal$LAYOUT, fftreal$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * FMOD_DSP_DFT_FFTREAL_FUNC fftreal
     * }
     */
    public static void fftreal(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(fftreal$LAYOUT, fftreal$OFFSET, fieldValue);
    }

    private static final AddressLayout inversefftreal$LAYOUT = (AddressLayout)$LAYOUT.select(groupElement("inversefftreal"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * FMOD_DSP_DFT_IFFTREAL_FUNC inversefftreal
     * }
     */
    public static final AddressLayout inversefftreal$layout() {
        return inversefftreal$LAYOUT;
    }

    private static final long inversefftreal$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * FMOD_DSP_DFT_IFFTREAL_FUNC inversefftreal
     * }
     */
    public static final long inversefftreal$offset() {
        return inversefftreal$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * FMOD_DSP_DFT_IFFTREAL_FUNC inversefftreal
     * }
     */
    public static MemorySegment inversefftreal(MemorySegment struct) {
        return struct.get(inversefftreal$LAYOUT, inversefftreal$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * FMOD_DSP_DFT_IFFTREAL_FUNC inversefftreal
     * }
     */
    public static void inversefftreal(MemorySegment struct, MemorySegment fieldValue) {
        struct.set(inversefftreal$LAYOUT, inversefftreal$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

