// Generated by jextract

package audio.fmod.panama;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct FMOD_DSP_PARAMETER_FFT {
 *     int length;
 *     int numchannels;
 *     float *spectrum[32];
 * }
 * }
 */
public class FMOD_DSP_PARAMETER_FFT {

    FMOD_DSP_PARAMETER_FFT() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FmodCore.C_INT.withName("length"),
        FmodCore.C_INT.withName("numchannels"),
        MemoryLayout.sequenceLayout(32, FmodCore.C_POINTER).withName("spectrum")
    ).withName("FMOD_DSP_PARAMETER_FFT");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt length$LAYOUT = (OfInt)$LAYOUT.select(groupElement("length"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int length
     * }
     */
    public static final OfInt length$layout() {
        return length$LAYOUT;
    }

    private static final long length$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int length
     * }
     */
    public static final long length$offset() {
        return length$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int length
     * }
     */
    public static int length(MemorySegment struct) {
        return struct.get(length$LAYOUT, length$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int length
     * }
     */
    public static void length(MemorySegment struct, int fieldValue) {
        struct.set(length$LAYOUT, length$OFFSET, fieldValue);
    }

    private static final OfInt numchannels$LAYOUT = (OfInt)$LAYOUT.select(groupElement("numchannels"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int numchannels
     * }
     */
    public static final OfInt numchannels$layout() {
        return numchannels$LAYOUT;
    }

    private static final long numchannels$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int numchannels
     * }
     */
    public static final long numchannels$offset() {
        return numchannels$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int numchannels
     * }
     */
    public static int numchannels(MemorySegment struct) {
        return struct.get(numchannels$LAYOUT, numchannels$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int numchannels
     * }
     */
    public static void numchannels(MemorySegment struct, int fieldValue) {
        struct.set(numchannels$LAYOUT, numchannels$OFFSET, fieldValue);
    }

    private static final SequenceLayout spectrum$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("spectrum"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float *spectrum[32]
     * }
     */
    public static final SequenceLayout spectrum$layout() {
        return spectrum$LAYOUT;
    }

    private static final long spectrum$OFFSET = 8;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float *spectrum[32]
     * }
     */
    public static final long spectrum$offset() {
        return spectrum$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float *spectrum[32]
     * }
     */
    public static MemorySegment spectrum(MemorySegment struct) {
        return struct.asSlice(spectrum$OFFSET, spectrum$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float *spectrum[32]
     * }
     */
    public static void spectrum(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, spectrum$OFFSET, spectrum$LAYOUT.byteSize());
    }

    private static long[] spectrum$DIMS = { 32 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * float *spectrum[32]
     * }
     */
    public static long[] spectrum$dimensions() {
        return spectrum$DIMS;
    }
    private static final VarHandle spectrum$ELEM_HANDLE = spectrum$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * float *spectrum[32]
     * }
     */
    public static MemorySegment spectrum(MemorySegment struct, long index0) {
        return (MemorySegment)spectrum$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * float *spectrum[32]
     * }
     */
    public static void spectrum(MemorySegment struct, long index0, MemorySegment fieldValue) {
        spectrum$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

