// Generated by jextract

package audio.fmod.panama;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef FMOD_RESULT (*FMOD_DSP_PAN_SUMSTEREOMATRIX_FUNC)(FMOD_DSP_STATE *, FMOD_SPEAKERMODE, float, float, float, int, float *)
 * }
 */
public class FMOD_DSP_PAN_SUMSTEREOMATRIX_FUNC {

    FMOD_DSP_PAN_SUMSTEREOMATRIX_FUNC() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        int apply(MemorySegment dsp_state, int sourceSpeakerMode, float pan, float lowFrequencyGain, float overallGain, int matrixHop, MemorySegment matrix);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        FmodCore.C_INT,
        FmodCore.C_POINTER,
        FmodCore.C_INT,
        FmodCore.C_FLOAT,
        FmodCore.C_FLOAT,
        FmodCore.C_FLOAT,
        FmodCore.C_INT,
        FmodCore.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = FmodCore.upcallHandle(FMOD_DSP_PAN_SUMSTEREOMATRIX_FUNC.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(FMOD_DSP_PAN_SUMSTEREOMATRIX_FUNC.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static int invoke(MemorySegment funcPtr,MemorySegment dsp_state, int sourceSpeakerMode, float pan, float lowFrequencyGain, float overallGain, int matrixHop, MemorySegment matrix) {
        try {
            return (int) DOWN$MH.invokeExact(funcPtr, dsp_state, sourceSpeakerMode, pan, lowFrequencyGain, overallGain, matrixHop, matrix);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

