// Generated by jextract

package audio.fmod.panama;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef float (*FMOD_3D_ROLLOFF_CALLBACK)(FMOD_CHANNELCONTROL *, float)
 * }
 */
public class FMOD_3D_ROLLOFF_CALLBACK {

    FMOD_3D_ROLLOFF_CALLBACK() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        float apply(MemorySegment channelcontrol, float distance);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        FmodCore.C_FLOAT,
        FmodCore.C_POINTER,
        FmodCore.C_FLOAT
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = FmodCore.upcallHandle(FMOD_3D_ROLLOFF_CALLBACK.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(FMOD_3D_ROLLOFF_CALLBACK.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static float invoke(MemorySegment funcPtr,MemorySegment channelcontrol, float distance) {
        try {
            return (float) DOWN$MH.invokeExact(funcPtr, channelcontrol, distance);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

