// Generated by jextract

package audio.fmod.panama;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct FMOD_DSP_PARAMETER_3DATTRIBUTES {
 *     FMOD_3D_ATTRIBUTES relative;
 *     FMOD_3D_ATTRIBUTES absolute;
 * }
 * }
 */
public class FMOD_DSP_PARAMETER_3DATTRIBUTES {

    FMOD_DSP_PARAMETER_3DATTRIBUTES() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FMOD_3D_ATTRIBUTES.layout().withName("relative"),
        FMOD_3D_ATTRIBUTES.layout().withName("absolute")
    ).withName("FMOD_DSP_PARAMETER_3DATTRIBUTES");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout relative$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("relative"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * FMOD_3D_ATTRIBUTES relative
     * }
     */
    public static final GroupLayout relative$layout() {
        return relative$LAYOUT;
    }

    private static final long relative$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * FMOD_3D_ATTRIBUTES relative
     * }
     */
    public static final long relative$offset() {
        return relative$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * FMOD_3D_ATTRIBUTES relative
     * }
     */
    public static MemorySegment relative(MemorySegment struct) {
        return struct.asSlice(relative$OFFSET, relative$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * FMOD_3D_ATTRIBUTES relative
     * }
     */
    public static void relative(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, relative$OFFSET, relative$LAYOUT.byteSize());
    }

    private static final GroupLayout absolute$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("absolute"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * FMOD_3D_ATTRIBUTES absolute
     * }
     */
    public static final GroupLayout absolute$layout() {
        return absolute$LAYOUT;
    }

    private static final long absolute$OFFSET = 48;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * FMOD_3D_ATTRIBUTES absolute
     * }
     */
    public static final long absolute$offset() {
        return absolute$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * FMOD_3D_ATTRIBUTES absolute
     * }
     */
    public static MemorySegment absolute(MemorySegment struct) {
        return struct.asSlice(absolute$OFFSET, absolute$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * FMOD_3D_ATTRIBUTES absolute
     * }
     */
    public static void absolute(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, absolute$OFFSET, absolute$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

