// Generated by jextract

package audio.fmod.panama;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct FMOD_DSP_PARAMETER_DYNAMIC_RESPONSE {
 *     int numchannels;
 *     float rms[32];
 * }
 * }
 */
public class FMOD_DSP_PARAMETER_DYNAMIC_RESPONSE {

    FMOD_DSP_PARAMETER_DYNAMIC_RESPONSE() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FmodCore.C_INT.withName("numchannels"),
        MemoryLayout.sequenceLayout(32, FmodCore.C_FLOAT).withName("rms")
    ).withName("FMOD_DSP_PARAMETER_DYNAMIC_RESPONSE");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt numchannels$LAYOUT = (OfInt)$LAYOUT.select(groupElement("numchannels"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int numchannels
     * }
     */
    public static final OfInt numchannels$layout() {
        return numchannels$LAYOUT;
    }

    private static final long numchannels$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int numchannels
     * }
     */
    public static final long numchannels$offset() {
        return numchannels$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int numchannels
     * }
     */
    public static int numchannels(MemorySegment struct) {
        return struct.get(numchannels$LAYOUT, numchannels$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int numchannels
     * }
     */
    public static void numchannels(MemorySegment struct, int fieldValue) {
        struct.set(numchannels$LAYOUT, numchannels$OFFSET, fieldValue);
    }

    private static final SequenceLayout rms$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("rms"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float rms[32]
     * }
     */
    public static final SequenceLayout rms$layout() {
        return rms$LAYOUT;
    }

    private static final long rms$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float rms[32]
     * }
     */
    public static final long rms$offset() {
        return rms$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float rms[32]
     * }
     */
    public static MemorySegment rms(MemorySegment struct) {
        return struct.asSlice(rms$OFFSET, rms$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float rms[32]
     * }
     */
    public static void rms(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, rms$OFFSET, rms$LAYOUT.byteSize());
    }

    private static long[] rms$DIMS = { 32 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * float rms[32]
     * }
     */
    public static long[] rms$dimensions() {
        return rms$DIMS;
    }
    private static final VarHandle rms$ELEM_HANDLE = rms$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * float rms[32]
     * }
     */
    public static float rms(MemorySegment struct, long index0) {
        return (float)rms$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * float rms[32]
     * }
     */
    public static void rms(MemorySegment struct, long index0, float fieldValue) {
        rms$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

