// Generated by jextract

package audio.fmod.panama;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct FMOD_DSP_LOUDNESS_METER_WEIGHTING_TYPE {
 *     float channelweight[32];
 * }
 * }
 */
public class FMOD_DSP_LOUDNESS_METER_WEIGHTING_TYPE {

    FMOD_DSP_LOUDNESS_METER_WEIGHTING_TYPE() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        MemoryLayout.sequenceLayout(32, FmodCore.C_FLOAT).withName("channelweight")
    ).withName("FMOD_DSP_LOUDNESS_METER_WEIGHTING_TYPE");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final SequenceLayout channelweight$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("channelweight"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float channelweight[32]
     * }
     */
    public static final SequenceLayout channelweight$layout() {
        return channelweight$LAYOUT;
    }

    private static final long channelweight$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float channelweight[32]
     * }
     */
    public static final long channelweight$offset() {
        return channelweight$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float channelweight[32]
     * }
     */
    public static MemorySegment channelweight(MemorySegment struct) {
        return struct.asSlice(channelweight$OFFSET, channelweight$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float channelweight[32]
     * }
     */
    public static void channelweight(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, channelweight$OFFSET, channelweight$LAYOUT.byteSize());
    }

    private static long[] channelweight$DIMS = { 32 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * float channelweight[32]
     * }
     */
    public static long[] channelweight$dimensions() {
        return channelweight$DIMS;
    }
    private static final VarHandle channelweight$ELEM_HANDLE = channelweight$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * float channelweight[32]
     * }
     */
    public static float channelweight(MemorySegment struct, long index0) {
        return (float)channelweight$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * float channelweight[32]
     * }
     */
    public static void channelweight(MemorySegment struct, long index0, float fieldValue) {
        channelweight$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

