// Generated by jextract

package audio.fmod.panama;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef FMOD_RESULT (*FMOD_OUTPUT_OBJECT3DALLOC_CALLBACK)(FMOD_OUTPUT_STATE *, void **)
 * }
 */
public class FMOD_OUTPUT_OBJECT3DALLOC_CALLBACK {

    FMOD_OUTPUT_OBJECT3DALLOC_CALLBACK() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        int apply(MemorySegment output_state, MemorySegment object3d);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        FmodCore.C_INT,
        FmodCore.C_POINTER,
        FmodCore.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = FmodCore.upcallHandle(FMOD_OUTPUT_OBJECT3DALLOC_CALLBACK.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(FMOD_OUTPUT_OBJECT3DALLOC_CALLBACK.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static int invoke(MemorySegment funcPtr,MemorySegment output_state, MemorySegment object3d) {
        try {
            return (int) DOWN$MH.invokeExact(funcPtr, output_state, object3d);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

