// Generated by jextract

package audio.fmod.panama;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef FMOD_RESULT (*FMOD_CODEC_METADATA_FUNC)(FMOD_CODEC_STATE *, FMOD_TAGTYPE, char *, void *, unsigned int, FMOD_TAGDATATYPE, int)
 * }
 */
public class FMOD_CODEC_METADATA_FUNC {

    FMOD_CODEC_METADATA_FUNC() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        int apply(MemorySegment codec_state, int tagtype, MemorySegment name, MemorySegment data, int datalen, int datatype, int unique);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        FmodCore.C_INT,
        FmodCore.C_POINTER,
        FmodCore.C_INT,
        FmodCore.C_POINTER,
        FmodCore.C_POINTER,
        FmodCore.C_INT,
        FmodCore.C_INT,
        FmodCore.C_INT
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = FmodCore.upcallHandle(FMOD_CODEC_METADATA_FUNC.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(FMOD_CODEC_METADATA_FUNC.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static int invoke(MemorySegment funcPtr,MemorySegment codec_state, int tagtype, MemorySegment name, MemorySegment data, int datalen, int datatype, int unique) {
        try {
            return (int) DOWN$MH.invokeExact(funcPtr, codec_state, tagtype, name, data, datalen, datatype, unique);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

