// Generated by jextract

package audio.fmod.panama;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct FMOD_DSP_PARAMETER_3DATTRIBUTES_MULTI {
 *     int numlisteners;
 *     FMOD_3D_ATTRIBUTES relative[8];
 *     float weight[8];
 *     FMOD_3D_ATTRIBUTES absolute;
 * }
 * }
 */
public class FMOD_DSP_PARAMETER_3DATTRIBUTES_MULTI {

    FMOD_DSP_PARAMETER_3DATTRIBUTES_MULTI() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        FmodCore.C_INT.withName("numlisteners"),
        MemoryLayout.sequenceLayout(8, FMOD_3D_ATTRIBUTES.layout()).withName("relative"),
        MemoryLayout.sequenceLayout(8, FmodCore.C_FLOAT).withName("weight"),
        FMOD_3D_ATTRIBUTES.layout().withName("absolute")
    ).withName("FMOD_DSP_PARAMETER_3DATTRIBUTES_MULTI");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt numlisteners$LAYOUT = (OfInt)$LAYOUT.select(groupElement("numlisteners"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int numlisteners
     * }
     */
    public static final OfInt numlisteners$layout() {
        return numlisteners$LAYOUT;
    }

    private static final long numlisteners$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int numlisteners
     * }
     */
    public static final long numlisteners$offset() {
        return numlisteners$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int numlisteners
     * }
     */
    public static int numlisteners(MemorySegment struct) {
        return struct.get(numlisteners$LAYOUT, numlisteners$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int numlisteners
     * }
     */
    public static void numlisteners(MemorySegment struct, int fieldValue) {
        struct.set(numlisteners$LAYOUT, numlisteners$OFFSET, fieldValue);
    }

    private static final SequenceLayout relative$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("relative"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * FMOD_3D_ATTRIBUTES relative[8]
     * }
     */
    public static final SequenceLayout relative$layout() {
        return relative$LAYOUT;
    }

    private static final long relative$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * FMOD_3D_ATTRIBUTES relative[8]
     * }
     */
    public static final long relative$offset() {
        return relative$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * FMOD_3D_ATTRIBUTES relative[8]
     * }
     */
    public static MemorySegment relative(MemorySegment struct) {
        return struct.asSlice(relative$OFFSET, relative$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * FMOD_3D_ATTRIBUTES relative[8]
     * }
     */
    public static void relative(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, relative$OFFSET, relative$LAYOUT.byteSize());
    }

    private static long[] relative$DIMS = { 8 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * FMOD_3D_ATTRIBUTES relative[8]
     * }
     */
    public static long[] relative$dimensions() {
        return relative$DIMS;
    }
    private static final MethodHandle relative$ELEM_HANDLE = relative$LAYOUT.sliceHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * FMOD_3D_ATTRIBUTES relative[8]
     * }
     */
    public static MemorySegment relative(MemorySegment struct, long index0) {
        try {
            return (MemorySegment)relative$ELEM_HANDLE.invokeExact(struct, 0L, index0);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * FMOD_3D_ATTRIBUTES relative[8]
     * }
     */
    public static void relative(MemorySegment struct, long index0, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, relative(struct, index0), 0L, FMOD_3D_ATTRIBUTES.layout().byteSize());
    }

    private static final SequenceLayout weight$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("weight"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * float weight[8]
     * }
     */
    public static final SequenceLayout weight$layout() {
        return weight$LAYOUT;
    }

    private static final long weight$OFFSET = 388;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * float weight[8]
     * }
     */
    public static final long weight$offset() {
        return weight$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * float weight[8]
     * }
     */
    public static MemorySegment weight(MemorySegment struct) {
        return struct.asSlice(weight$OFFSET, weight$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * float weight[8]
     * }
     */
    public static void weight(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, weight$OFFSET, weight$LAYOUT.byteSize());
    }

    private static long[] weight$DIMS = { 8 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * float weight[8]
     * }
     */
    public static long[] weight$dimensions() {
        return weight$DIMS;
    }
    private static final VarHandle weight$ELEM_HANDLE = weight$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * float weight[8]
     * }
     */
    public static float weight(MemorySegment struct, long index0) {
        return (float)weight$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * float weight[8]
     * }
     */
    public static void weight(MemorySegment struct, long index0, float fieldValue) {
        weight$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final GroupLayout absolute$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("absolute"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * FMOD_3D_ATTRIBUTES absolute
     * }
     */
    public static final GroupLayout absolute$layout() {
        return absolute$LAYOUT;
    }

    private static final long absolute$OFFSET = 420;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * FMOD_3D_ATTRIBUTES absolute
     * }
     */
    public static final long absolute$offset() {
        return absolute$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * FMOD_3D_ATTRIBUTES absolute
     * }
     */
    public static MemorySegment absolute(MemorySegment struct) {
        return struct.asSlice(absolute$OFFSET, absolute$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * FMOD_3D_ATTRIBUTES absolute
     * }
     */
    public static void absolute(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, absolute$OFFSET, absolute$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

